feat: add luasnip

diff --git a/profile/.config/nvim/snippets/sh.yaml b/profile/.config/nvim/snippets/sh.yaml
--- a/profile/.config/nvim/snippets/sh.yaml
+++ b/profile/.config/nvim/snippets/sh.yaml
@@ -1,24 +1,3 @@
-shebang:
-  prefix:
-    - "#!"
-    - shebang
-  body: |-
-    #!/usr/bin/env -S bash
-
-    set -Eeuo pipefail
-    trap 'echo "⚠  Error (\$0:\$LINENO, exit code: \$?): \$BASH_COMMAND" >&2' ERR
-
-    $1
-if-else:
-  prefix: if
-  body: |-
-    if [[ $1 ]]; then
-        $2
-    elif [[ $3 ]]; then
-        $4
-    else
-        $6
-    fi
 case:
   prefix: case
   body: |-
@@ -30,18 +9,39 @@ case:
             exit 1
             ;;
     esac
-function:
-  prefix: function
-  body: |-
-    function $1() {
-        $2
-    }
+echo:
+  prefix: echo
+  body: echo $1
 for:
   prefix: for
   body: |-
     for $1 in $2; do
         $3
     done
-echo:
-  prefix: echo
-  body: echo $1
+function:
+  prefix: function
+  body: |-
+    function $1() {
+        $2
+    }
+if-else:
+  prefix: if
+  body: |-
+    if [[ $1 ]]; then
+        $2
+    elif [[ $3 ]]; then
+        $4
+    else
+        $6
+    fi
+shebang:
+  prefix:
+    - "#!"
+    - shebang
+  body: |-
+    #!/usr/bin/env -S bash
+
+    set -Eeuo pipefail
+    trap 'echo "⚠  Error (\$0:\$LINENO, exit code: \$?): \$BASH_COMMAND" >&2' ERR
+
+    $1
